"use client"

import './globals.scss'
import React from "react";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>
      <ReactQueryProvider>
        <main>{children}</main>
      </ReactQueryProvider>
     </body>
    </html>
  )
}
